/* eslint-disable id-length */
module.exports = {
  REQUEST_CORRELATION_NAMESPACE_KEY: 'umbrel-manager-request',
  REQUEST_CORRELATION_ID_KEY: 'reqId',
  DEVICE_HOSTNAME: process.env.DEVICE_HOSTNAME || 'umbrel.local',
  ethereum_P2P_HIDDEN_SERVICE: process.env.ethereum_P2P_HIDDEN_SERVICE,
  ethereum_RPC_HIDDEN_SERVICE: process.env.ethereum_RPC_HIDDEN_SERVICE,
  ethereum_RPC_USER: process.env.ethereum_RPC_USER || 'umbrel',
  ethereum_RPC_PASSWORD: process.env.ethereum_RPC_PASSWORD || 'moneyprintergobrrr',
  DEVICE_DOMAIN_NAME: process.env.DEVICE_DOMAIN_NAME,
  JSON_STORE_FILE: process.env.JSON_STORE_FILE || "/data/ethereum-config.json",
  UMBREL_ethereum_CONF_FILEPATH: process.env.UMBREL_ethereum_CONF_FILE || "/ethereum/.ethereum/umbrel-ethereum.conf",
  ethereum_CONF_FILEPATH: process.env.ethereum_CONF_FILE || "/ethereum/.ethereum/ethereum.conf",
  ethereum_INITIALIZE_WITH_CLEARNET_OVER_TOR: process.env.ethereum_INITIALIZE_WITH_CLEARNET_OVER_TOR === 'true',
  ethereum_P2P_PORT: process.env.ethereum_P2P_PORT || 8333,
  ethereum_RPC_PORT: process.env.ethereum_RPC_PORT || 8332,
  ethereum_DEFAULT_NETWORK: process.env.ethereum_DEFAULT_NETWORK || "mainnet",
  ethereumD_IP: process.env.ethereumD_IP,
  TOR_PROXY_IP: process.env.TOR_PROXY_IP,
  TOR_PROXY_PORT: process.env.TOR_PROXY_PORT,
  TOR_PROXY_CONTROL_PORT: process.env.TOR_PROXY_CONTROL_PORT,
  TOR_PROXY_CONTROL_PASSWORD: process.env.TOR_PROXY_CONTROL_PASSWORD,
  I2P_DAEMON_IP: process.env.I2P_DAEMON_IP,
  I2P_DAEMON_PORT: process.env.I2P_DAEMON_PORT
};